In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)  # [3. 4. 5. 6. 7.]
print(a - 1)  # [0. 1. 2. 3. 4.]

[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


In [4]:
nnvect= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(nnvect)                

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
m = np.array([[0, 0, 0], [0, 0, 0]], dtype=int)

print(m)

[[0 0 0]
 [0 0 0]]


In [6]:
random_array = np.random.randint(1, 11, size=(5, 5))
print(random_array)

[[ 2  9  2  1 10]
 [ 9  4 10  8  4]
 [ 3  2  3  6  9]
 [ 2  7  1  2 10]
 [ 1  7  3  3  9]]


In [8]:
random_array = np.random.rand(4, 4)
print(random_array)
rounded_array = np.round(random_array, 3)
print(rounded_array)

[[0.91307199 0.32982247 0.48558636 0.44500471]
 [0.12682399 0.48464156 0.17475126 0.81486698]
 [0.53428994 0.11336481 0.02204822 0.40206168]
 [0.89938025 0.51630273 0.4462885  0.42764792]]
[[0.913 0.33  0.486 0.445]
 [0.127 0.485 0.175 0.815]
 [0.534 0.113 0.022 0.402]
 [0.899 0.516 0.446 0.428]]


In [2]:
import numpy as np
np.random.seed(42)
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
add_res = a + b
sub_res = a - b
mul_res = a*b
print ('a:', a)
print ('b:', b)
print ('add:', add_res)
print ('sub:', sub_res)
print ('mul:', mul_res)

ModuleNotFoundError: No module named 'numpy'