<a href="https://colab.research.google.com/github/Serhii-progrmr/Python-DS-Homework/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Одновимірний масив (вектор) з першими 10-ма натуральними числами

In [ ]:
#1 Одновимірний масив (вектор) з першими 10-ма натуральними числами
nnvect= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# print(nnvect)
nnvect

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Двовимірний масив (матрицю) розміром 3x3, заповніть його нулями

In [ ]:
#2 Двовимірний масив (матрицю) розміром 3x3, заповніть його нулями
m = np.array([[0, 0, 0], [0, 0, 0]], dtype=int)

print(m)

[[0 0 0]
 [0 0 0]]


3. масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
#3 масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
random_array = np.random.randint(1, 11, size=(5, 5))
print(random_array)

[[ 2  9  2  1 10]
 [ 9  4 10  8  4]
 [ 3  2  3  6  9]
 [ 2  7  1  2 10]
 [ 1  7  3  3  9]]


4. Масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення

In [ ]:
#4 масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення
random_array = np.random.rand(4, 4)
print(random_array)
rounded_array = np.round(random_array, 3)
print(rounded_array)

[[0.91307199 0.32982247 0.48558636 0.44500471]
 [0.12682399 0.48464156 0.17475126 0.81486698]
 [0.53428994 0.11336481 0.02204822 0.40206168]
 [0.89938025 0.51630273 0.4462885  0.42764792]]
[[0.913 0.33  0.486 0.445]
 [0.127 0.485 0.175 0.815]
 [0.534 0.113 0.022 0.402]
 [0.899 0.516 0.446 0.428]]


5. два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
#5 два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте
#  на них поелементні операції додавання, віднімання та множення.
import numpy as np
np.random.seed(42)
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
add_res = a + b
sub_res = a - b
mul_res = a*b
print ('a:', a)
print ('b:', b)
print ('add:', add_res)
print ('sub:', sub_res)
print ('mul:', mul_res)

a: [7 4 8 5 7]
b: [10  3  7  8  5]
add: [17  7 15 13 12]
sub: [-3  1  1 -3  2]
mul: [70 12 56 40 35]


6. два вектори розміром 7, заповніть довільними числами та знайдіть та знайдіть їх скалярний добуток

In [ ]:
#6 два вектори розміром 7, заповніть довільними числами та знайдіть скалярний добуток векторів
np.random.seed(42)
v1 = np.random.randint(1, 11, size=7)
v2 = np.random.randint(1, 11, size=7)
print(v1, v2)
print(np.dot(v1, v2))

[ 7  4  8  5  7 10  3] [7 8 5 4 8 8 3]
286


7. дві матриці розміром 2x2 та 2x3, заповнити їх випадковими цілими числами в діапазоні від 1 до 10 та перемножити їх між собою.

In [ ]:
#7 дві матриці розміром 2x2 та 2x3, заповнити їх випадковими цілими числами в діапазоні від 1 до 10 та перемножити їх між собою.
np.random.seed(42)
m1 = np.random.randint(1, 10, size=(2, 2))
m2 = np.random.randint(1, 10, size=(2, 3))
print(m1)
print(m2)
print(m1*m1)


[[7 4]
 [8 5]]
[[7 3 7]
 [8 5 4]]
[[49 16]
 [64 25]]
[[81 41 65]
 [96 49 76]]


8. матриця розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
#8 матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
np.random.seed(42)
a = np.random.randint(1, 10, size=(3, 3))
a_inv = np.linalg.inv(a)
print('a:',a)
print('a_inv:',a_inv)

a: [[7 4 8]
 [5 7 3]
 [7 8 5]]
a_inv: [[-1.         -4.          4.        ]
 [ 0.36363636  1.90909091 -1.72727273]
 [ 0.81818182  2.54545455 -2.63636364]]


9. матриця розміром 4x4, заповнити її випадковими дійсними числами в діапазоні від 0 до 1 та транспонувати.

In [ ]:
#9 транспонування матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
np.random.seed(42)
a = np.round(np.random.rand(4, 4), 2)
print(a)
tr_a = a.T
print(tr_a)

[[0.37 0.95 0.73 0.6 ]
 [0.16 0.16 0.06 0.87]
 [0.6  0.71 0.02 0.97]
 [0.83 0.21 0.18 0.18]]
[[0.37 0.16 0.6  0.83]
 [0.95 0.16 0.71 0.21]
 [0.73 0.06 0.02 0.18]
 [0.6  0.87 0.97 0.18]]


10. матриця розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор

In [ ]:
#10 перемножте матрицю на вектор
import numpy as np
np.random.seed(42)
m = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=4)
c = np.dot(m,v)
print(m)
print(v)
print(c)

[[ 7  4  8  5]
 [ 7 10  3  7]
 [ 8  5  4  8]]
[8 3 6 5]
[141 139 143]


11. матриця розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор

In [ ]:
#11 матриця розміром 2x3 та вектор розміром 3, перемножити матрицю на вектор
np.random.seed(42)
m = np.random.rand(2, 3)
v = np.random.rand(3)
c = np.round(np.dot(m,v),3)
print(m)
print(v)
print(c)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[0.05808361 0.86617615 0.60111501]
[1.285 0.264]


12.	Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
#12 поелементне множення 2-х матриць
np.random.seed(42)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print(m1)
print(m2)
print(m1*m2)
#print(np.multiply(m1, m2))

[[7 4]
 [8 5]]
[[ 7 10]
 [ 3  7]]
[[49 40]
 [24 35]]


13. дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
#13 добуток 2-х матриць
np.random.seed(42)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print(m1)
print(m2)
mlt = np.dot(m1, m2)
print(mlt)

[[7 4]
 [8 5]]
[[ 7 10]
 [ 3  7]]
[[ 61  98]
 [ 71 115]]


14. матриця розміром 5x5, заповнити її випадковими цілими числами в діапазоні від 1 до 100 та знайти суму елементів матриці.

In [ ]:
#14 сума елементів матриці
np.random.seed(42)
m = np.random.randint(1, 101, size=(5, 5))
print(m)
sum_el = np.sum(m)
print(sum_el)

[[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]]
1262


15.дві матриці розміром 4x4, заповнити їх випадковими цілими числами в діапазоні від 1 до 10 та знайти їхню різницю

In [ ]:
#15 різниця матриць
m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
diff = m1-m2
print(m1)
print(m2)
print(diff)

[[10  6  9  1]
 [10  3  7  4]
 [ 9  3  5  3]
 [ 7  5  9  7]]
[[ 2  4  9  2]
 [10  9 10  5]
 [ 2  4  7  8]
 [ 3  1  4  2]]
[[ 8  2  0 -1]
 [ 0 -6 -3 -1]
 [ 7 -1 -2 -5]
 [ 4  4  5  5]]


16. матриця розміром 3x3, заповнити її випадковими дійсними числами в діапазоні від 0 до 1 та знайти вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
#16 сума елементів кожного рядка матриці
m = np.round(np.random.rand(3, 3), 3)
row_sum = np.sum(m, axis =1)
col_v = np.round(row_sum.reshape(-1, 1), 3)
print(m)
print(col_v)


[[0.623 0.331 0.064]
 [0.311 0.325 0.73 ]
 [0.638 0.887 0.472]]
[[1.018]
 [1.366]
 [1.997]]


17. матриця розміром 3x3, заповнити її випадковими дійсними числами в діапазоні від 0 до 1 та знайти вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
#17 матриця з квадратами довільних чисел
np.random.seed(42)
m1 = np.random.randint(1, 20, size=(3, 4))
print(m1)
print(m1*m1)



[[ 7 15 11  8]
 [ 7 19 11 11]
 [ 4  8  3  2]]
[[ 49 225 121  64]
 [ 49 361 121 121]
 [ 16  64   9   4]]


18. вектор розміром 4, заповнити його випадковими цілими числами в діапазоні від 1 до 50 та знайти вектор з квадратними коренями цих чисел.

In [ ]:
#18 вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
v = np.random.randint(1, 51, size=4)
sqrt_v = np.sqrt(v)
print(v)
print(sqrt_v)



[ 2 21 33 12]
[1.41421356 4.58257569 5.74456265 3.46410162]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
